### ISSUE TITLE
FlySky AFHDS2A: problems using together with FS-i6s

### ISSUE THREAD

**Issue by wimalopaan** [pascallanger/DIY-Multiprotocol-TX-Module#422] opened 2020-08-31 06:16 UTC
Following setup gives reproducible telemetry problems:

1. radio: Radiomaster TX16s with internal module (latest firmware)
2. radio: FlySky FS-i6s
both receivers: FS-ia6B

The RX are at the same position. Moving both TX to a distant location results in loss of telemetry at the very same point on both TX. This is reproducible. Using only one TX (anyone) no problem arises.

**Comment by pascallanger** [comment] 2020-08-31 06:21
Sounds to me that Multi is doing the same as Flysky from your description which is good.
It looks like that the TXs are swamping each others.
Not sure I can do anything... Have you opened a case with Flysky since it's also affecting their TX?

**Comment by wimalopaan** [comment] 2020-08-31 06:24
Do you have teh HW to reproduces that?

Will check with FlySky also.

**Comment by pascallanger** [comment] 2020-08-31 06:30
I don't have any Flysky radio.
What you can try to do is to put Multi in low power mode, I would expect the FS-i6s to recover telemetry.

**Comment by wimalopaan** [comment] 2020-08-31 06:33
But this results in very low possible range for the RM?

Can this be an issue with some sort of EU-LBT?

**Comment by pascallanger** [comment] 2020-08-31 07:06
The test I was asking would show that the issue is swamping.
There is no LBT on this protocol. In fact you are not losing the control of the RX which shows that theTX to RX works. It's RX to TX.

**Comment by MartyHugh** [comment] 2020-08-31 11:18
Sounds like your two RXs are too close together.  They are both transmitting telemetry and are talking over each other.  What happens when you separate them by 12 inches ?

**Comment by wimalopaan** [comment] 2020-09-07 15:24
The same effect arises with two RadioMaster with internal MPM and two FlySky FS-iA6b receiver. The receivers are seperated by more than 3 meters. The TX are seperated by 2-4 meters.

What tests should we perform to help with this issue?

**Comment by pascallanger** [comment] 2020-09-07 15:47
The tests in asked for may be?

**Comment by pascallanger** [comment] 2020-09-07 15:49
And again you are taking about 2 multi modules. What about 2 genuine flysky radios. Are they doing any better?

**Comment by wimalopaan** [comment] 2020-09-20 18:02
Looks like duplicate of #398

**Comment by pascallanger** [comment] 2020-09-20 20:21
This has nothing to do with it but since you think it is related I'm closing this issue
Note that you still haven't replied to any of my questions to pinpoint your issue since 21 days...

**Closed by pascallanger** 2020-09-20 20:21 UTC
Labels: question

**Comment by wimalopaan** [comment] 2020-09-21 03:16
I will come back with tests, but this will take time until the next weekend.

Is it sufficient to do the test with to MPM, one with reduced power?

**Comment by wimalopaan** [comment] 2020-09-24 05:40
Please help use with the needed test procedure (see post above). 

What tests and what infos do you need?
