### ISSUE TITLE
Hitec Red AFHSS Support

### ISSUE THREAD

**Issue by z3r0c00l2005** [pascallanger/DIY-Multiprotocol-TX-Module#161] opened 2018-05-02 12:42 UTC
Hi Guys, it woudl be great to see support for the Hitec Red protocol as used for the Ares range of indoor/park flyers (I believe this is the same as the Minima protocol)

**Comment by pascallanger** [comment] 2018-05-04 14:01
I need a Hitec transmitter and a RX to reverse the protocol...

**Comment by z3r0c00l2005** [comment] 2018-05-04 14:04
Only kit I've got is embedded in RTF Ares models.  Can hook up a logic analyser to the tx if that'll help

**Comment by pascallanger** [comment] 2018-05-04 14:06
You can always see if you have access to the spi bus between the controller and the RF component if not all integrated in one chip.
Let me know.

**Comment by z3r0c00l2005** [comment] 2018-05-06 09:48
[pwr on to bound.zip](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/1977499/pwr.on.to.bound.zip)

I've attached a LA to the 3 non-power pins between the main controller board (Processor seems to be a ATMEGA48V-10U) and the RF module (FLDSTX1) and captured the power-on trace.

The Reciever was powered up, and the TX turned on and left to negotiate the link.

D0 is connected to FLDSTX1 pin 8
D1 to pin 6
D2 to pin 7

Other than the power pins, none of the others are soldered up so i've assumed they're unused

Attached trace is from Pulseview.

**Comment by z3r0c00l2005** [comment] 2018-05-08 06:37
![rf_module_no shield](https://user-images.githubusercontent.com/4502949/39741635-9546f78a-5292-11e8-8730-e567420111b0.JPG)
![mainboard](https://user-images.githubusercontent.com/4502949/39741662-ac59bc1e-5292-11e8-8bea-b4f1829e1c29.JPG)

Had the chance to dig further - the RF module is based upon the CC2510.

**Comment by pascallanger** [comment] 2018-05-09 16:47
The CC2510 is an all in one micro controller + RF. I'll have a look at what's going in between the main board and the rf module but little hope to find anything usefull...
We need a TX with a separated RF component. Or attack over the air which requires a lot more work...

**Comment by z3r0c00l2005** [comment] 2018-05-09 17:00
I was wandering that, especially since I didn't spot a clock signal for SPI. I was trying to assess from some of the FCC photos of there was a "budget" Hitec system that would be easier to sniff... Not sure I could see anything helpful on there. What would we need for OTA analysis?

**Comment by z3r0c00l2005** [comment] 2018-05-15 10:10
OK, I've taken the plunge and started looking Over The Air at this using a Hack RF One.

Does anyone have a GNU Radio Flow Graph for capturing FHSS systems?

looking at https://apps.fcc.gov/eas/GetApplicationAttachment.html?id=2808483 the frequency hopping tables are known (and confirmed with a spectrum sweep) using GFSK modulation should be plausible to decode the signals.

**Comment by pascallanger** [comment] 2018-05-15 10:38
I can't access the web page link since it's asking for a username/password. 
You could try to capture only one channel for now to see if some of the serial data can be located in the frame.

**Comment by z3r0c00l2005** [comment] 2018-05-15 10:43
Odd, although the link points to the "Test Report" for FCC ID 2AEIGFLDSTX1, pages 5 & 6 seem to be the most interesting ones.  I'll try to capture a bind packet from a couple of channels later.

**Comment by brandond** [comment] 2018-05-16 23:56
FWIW, I think you have to go through the application search to get at the documents:
https://apps.fcc.gov/oetcf/eas/reports/ViewExhibitReport.cfm?mode=Exhibits&RequestTimeout=500&calledFromFrame=N&application_id=UZY6Tq53n5Xm6H7eTSYdTA%3D%3D&fcc_id=2AEIGFLDSTX1

**Comment by FXDUTRUCROSSET** [comment] 2018-07-07 12:31
Pascal i live in the south of paris and can lend you a telemetry 9 ch receiver and tx module or full radio gear for a few if needed

**Comment by pascallanger** [comment] 2018-07-07 12:48
That would be cool. I work in Meudon so we should be able to meet somewhere. Please contact by PM.
FYI, Franck contacted me a while back to get the Assan protocol on multi. He didn't sent me the hardware but one of his friend did.

**Comment by FXDUTRUCROSSET** [comment] 2018-07-07 12:50
i'm on paris on friday sat sun i don't see the link for PM on git, pls contact me on modelisme.com fxdr MP

**Comment by z3r0c00l2005** [comment] 2018-07-13 06:54
I've now got access to a Spectra module, which seems to have qty 2 6-pin connectors between the main and RF boards - when i get chance i'll hook up the LA and post some traces.

**Comment by pascallanger** [comment] 2018-07-20 12:35
Any news?

**Comment by FXDUTRUCROSSET** [comment] 2018-07-21 00:16
i need to wait till u come back from hollidays in normandy?


Le ven. 20 juil. 2018 à 14:54, pascallanger <notifications@github.com> a
écrit :

**Comment by pascallanger** [comment] 2018-07-31 17:00
FYI, FX sent me an Hitec TX and RX (optima). I'm planning to work on this protocol in the next few days.
The TX has 2 modes to work with optima RXs or minima/micro RXs.
I don't have a minima/micro RX. If you have one available and don't mind to send it my way that would be appreciated. Otherwise if at least someone could participate in the debug seesion.

**Comment by pascallanger** [comment] 2018-07-31 17:04
I've already connected the wires on the spi bus and done my first dump. Everything looks good since I can see the cc2500 init and packets. Now the fun part starts.

**Comment by z3r0c00l2005** [comment] 2018-07-31 17:12
I've got an irange+ module and 3 models that bind with a minima protocol (although they're not genuine HiTec recievers). More than happy to help out :)

**Comment by pascallanger** [comment] 2018-08-01 16:41
Optima and Minima protocols and bind are pretty much reversed at this stage.
The telemetry for Optima is somewhat not fully there yet. I think it's because I'm missing either a sensor on the RX side so it has more data to send or on the TX side nothing is polling on the i2c bus the data. 
But telemetry is for later, I need now to put it in Multi and get what is on paper working ;-)

**Comment by pascallanger** [comment] 2018-08-03 10:27
I've got Minima "potentially" working. I was planning to push it on github today for you to test. I can share the dumps, maybe temporarely on this github for ease of access.
Optima does not work yet since I'm missing a small part of the bind negociation which I won't be able to work on until monday...

**Comment by z3r0c00l2005** [comment] 2018-08-03 10:30
Sounds good to me, I'll have the environment ready this afternoon to be able to recompile and check minima over the weekend - also well timed as i'll be able to test in a flying environment on monday as well :)

**Comment by pascallanger** [comment] 2018-08-03 10:38
I hope it will work for Minima, there is a number of unknown bytes and no RX to try out so... But since there is no negociation/talk between the TX and RX it should be ok.
I've put 2 dumps here: https://we.tl/UQFwCungJv

**Comment by z3r0c00l2005** [comment] 2018-08-03 11:01
Cool, thanks :) look forward to testing it out :)

I assume it's not going to be selectable via the OpenTX menu just yet and will use the usual AETR order on the model config

**Comment by pascallanger** [comment] 2018-08-03 11:05
On OpenTX, it will be custom protocol=39, sub-protocol=1 (for minima) and option=freq adjustment (like all frsky, corona,...)

**Comment by schwabe** [comment] 2018-08-03 11:05
@z3r0c00l2005 you can always use custom on OpenTX and use the protocol numbers.

**Comment by schwabe** [comment] 2018-08-03 11:17
@pascallanger I am adding Hitec (39) with Optima (0) and Minima (1) and cc2500 freq adj to OpenTX, right?

**Comment by pascallanger** [comment] 2018-08-03 12:33
@schwabe Yes please ;-)

**Comment by pascallanger** [comment] 2018-08-03 14:16
Ok, I can get an Optima receiver to move a servo.
Issues that I still observe:
 - if I use a random hopping table the link is not good, I'm seeing delays on the servo. This means to me that some channels are not usable, now I need to figure out which ones... The channels do not seem to be linked the ID, but there is still 3 unknown bytes which are exchanged during bind which I have no idea what to do with so still some investigations are needed.
 - telemetry packets are not received after some time. Relaunching the protocol restarts the telemetry stream but it will faill again. On the telemetry, I can get the RX voltage, TX LSSI and TX LQI. RX RSSI is not available...
Slowly but surely...

**Comment by pascallanger** [comment] 2018-08-03 14:22
@schwabe I'll do the same than AFHDS2A for the telemetry: FrSky Hub and forward to TX.
For now I'm using FrSky Hub but anyway I haven't figured out to get all the telemetry since the receiver is only sending the 1st frame on 4 (same on the original radio). It could be bacause there is no sensor attached, or the TX not having a device pulling telemetry.
So this is more a head's up that this is coming. Telemetry has GPS, temp sensors, voltage, rpm,...

**Comment by pascallanger** [comment] 2018-08-03 15:27
Ok, Optima RX is working:
 - Random ID and hopping frequency table
 - Telemetry is looks stable now, I have the RX voltage, TX RSSI and TX LQI through the FrSky Hub telemetry protocol.

TODO:
 - test on Minima -> there is a big chance that it works out of the box if I haven't done a mistake
 - Optima telemetry: how to request the next telemetry frame? Is it the RX deciding to send the frames or the TX? no idea for now...

**Comment by z3r0c00l2005** [comment] 2018-08-03 15:36
Awesome. I can take a look at the minima if you like. Is there a dev branch available?

**Comment by pascallanger** [comment] 2018-08-03 16:30
I've just made a push on the main repo.
Please test and report!

**Comment by z3r0c00l2005** [comment] 2018-08-04 07:35
Minima - 
Bound straight away

Seems to be a delay or a step on the channels, if i move the sticks to full deflection the servos respond in steps rather than a smooth motion

**Comment by pascallanger** [comment] 2018-08-04 08:42
Could you edit the hitec_cc2500.ino file and uncomment the line #define HITEC_FORCE_ID ?
It will use the ID and freq hopping of the TX I've dumped. Let me know if it improves or not.

**Comment by z3r0c00l2005** [comment] 2018-08-04 08:58
That seems to make it much worse

**Comment by pascallanger** [comment] 2018-08-04 13:32
Ok I'll see what I can do later this evening.

**Comment by pascallanger** [comment] 2018-08-04 17:14
I've been thinking about on the road... Have you tuned the frequency using option? What you describe could also be due by a bad freq tuning...

**Comment by z3r0c00l2005** [comment] 2018-08-04 18:38
Now I will admit I've not tried that since it all bound easily! What sort of values would you suggest trying?

**Comment by pascallanger** [comment] 2018-08-04 18:52
Follow the frsky/corona/sfhss freq tuning page: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Frequency_Tuning.md

**Comment by pascallanger** [comment] 2018-08-04 18:53
The freq tuning is module dependant so I can't give you numbers...

**Comment by z3r0c00l2005** [comment] 2018-08-05 07:49
Even tuned it doesn't appear to be smooth, although it's certainly closer to being flyable :)

**Comment by pascallanger** [comment] 2018-08-05 07:52
Have you retried once tuned  with force ID?

**Comment by z3r0c00l2005** [comment] 2018-08-05 07:56
with the forced ID ther's around a 2second delay between stick input and control deflection

**Comment by z3r0c00l2005** [comment] 2018-08-05 08:33
I can do, would I just upload a new build over serial and leave the TX connected to the PC to see that? (Usually I use a USB upload)

**Comment by pascallanger** [comment] 2018-08-05 08:48
Upload using USB, leave the module connected to USB and open the serial monitor from Arduino. You should see the module starting and giving you some information like protocol selected...

**Comment by pascallanger** [comment] 2018-08-05 09:32
You can do the same using serial just to be able to move forward... Exact same process but ftdi instead of USB.

**Comment by z3r0c00l2005** [comment] 2018-08-05 09:41
The only message dumped is for the selected protocol, nothing else in either bind or normal mode

**Comment by pascallanger** [comment] 2018-08-05 13:49
I've just published v1.2.0.25 adding the F5s in the packets.
Could you test Minima again with this version?

**Comment by pascallanger** [comment] 2018-08-05 18:09
Are you able to do a range test? Like do a sweep test on a servo and walk away with the receiver?
I really have no idea what the 2 bytes do. I've reproduced the real TX but since they vary... On my side I've used a fix value.

**Comment by pascallanger** [comment] 2018-08-05 18:17
I'll do some tests tomorrow and see if I can get a correlation with something.

**Comment by pascallanger** [comment] 2018-08-05 18:32
Yes the range option limits the module power output of any loaded protocol.
I need to check more carefully on the dumps if I can find out a correlation.

**Comment by pascallanger** [comment] 2018-08-06 16:36
Please check the latest version 1.2.0.26 which has some improvements:
 - 3 bytes TX ID
 - F5 frames same as the original TX
Still missing:
 - full telemetry

**Comment by z3r0c00l2005** [comment] 2018-08-06 18:46
Ok, on 1.2.0.25.....

Fokker binds and works well with Rx id 21....very juddery on id 01 or 11

Sopwith and spas jerky on any id, slightly better after tuning but not flyable

**Comment by pascallanger** [comment] 2018-08-06 18:56
I thought you said it was working?
What do you mean by rx id?

**Comment by z3r0c00l2005** [comment] 2018-08-06 19:06
On the bench the Fokker was ok, I'd just not tried the others yet

The Reciever number parameter in open TX

**Comment by z3r0c00l2005** [comment] 2018-08-06 19:09
I've a couple of flights in on the Fokker bound with ID 21 and it's great. I can only guess that the 3 recievers are slightly different in resilience, although they all work ok with the HiTec module. 

For testing I've been using the same model setup on the transmitter, just rebinding with the different models

**Comment by pascallanger** [comment] 2018-08-06 19:09
RX_num is between 0 and 15. That's why it sounded strange.
Have you tired 1.2.0.26 yet?

**Comment by z3r0c00l2005** [comment] 2018-08-06 19:10
I'll reflash hopefully in the next couple of days. Didn't have chance before coming flying :)

**Comment by pascallanger** [comment] 2018-08-07 11:43
Please use v1.2.027 for further testings of Minima/Micro receivers. I think I've nailed down the bug which was an overlook during implementation...

**Comment by z3r0c00l2005** [comment] 2018-08-07 11:55
Will do, just flashed 1.2.0.27 although need to head back to work now (why is there never enough free time!))  will hopefully get to try binding the models tonight and feedback when i get chance.

**Comment by z3r0c00l2005** [comment] 2018-08-07 16:14
I think we (well I say "we" but I really mean you!) are just about there :)

Flashed 1.2.0.27 and bound all 3 separate models using rx nums 1, 2 and 3, no Optional offset needed and all 3 receivers are responding smoothly on throttle, aileron and rudder channels.

Great work Pascal, much appreciated :)

**Comment by pascallanger** [comment] 2018-08-07 16:47
Cool! Minima/micro are OK.
Full telemetry is done as well. I still need to document and push the new code to GitHub but basically it's done.

**Comment by pascallanger** [comment] 2018-08-09 08:51
Closing the thread since both Optima + telemetry and Minima are working.

Pascal

**Closed by pascallanger** 2018-08-09 08:51 UTC
